# Generated by Django 6.0.1 on 2026-01-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_seed_locations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="asset",
            name="date_modified",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
