# Generated by Django 6.0.1 on 2026-01-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0003_remove_asset_created_at_remove_asset_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="date_modified",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
