# Generated by Django 6.0.1 on 2026-01-17 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0004_alter_asset_date_modified"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.RenameField(
            model_name="asset",
            old_name="date_modified",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="asset",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="register.department",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="staff_name",
            field=models.CharField(
                blank=True,
                help_text="Staff name as at time of asset assignment",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devicestatus",
            name="name",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("in_use", "In Use"),
                    ("spare", "Spare"),
                    ("decommissioned", "Decommissioned"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
