# Generated by Django 6.0.1 on 2026-01-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0006_alter_asset_options_remove_asset_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="assigned_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
