# Generated by Django 6.0.1 on 2026-01-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0007_auditlog_assigned_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditlog",
            name="action",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="changes",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="field_name",
            field=models.CharField(default="system", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auditlog",
            name="new_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="old_value",
            field=models.TextField(blank=True, null=True),
        ),
    ]
