# Generated by Django 6.0.1 on 2026-01-18 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "register",
            "0008_remove_auditlog_action_remove_auditlog_assigned_to_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
