# Generated by Django 6.0.1 on 2026-01-18 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0009_asset_created_at_asset_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="action",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auditlog",
                to="register.asset",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="field_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
