# Generated by Django 6.0 on 2026-02-02 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0010_auditlog_action_alter_auditlog_asset_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="updated_by",
        ),
    ]
