# Generated by Django 6.0 on 2026-02-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0013_dashboard_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aduser",
            name="department",
        ),
        migrations.RemoveField(
            model_name="aduser",
            name="office_location",
        ),
        migrations.DeleteModel(
            name="AssetMetrics",
        ),
        migrations.DeleteModel(
            name="DashboardCache",
        ),
        migrations.DeleteModel(
            name="ADUser",
        ),
    ]
