# Generated by Django 6.0 on 2026-02-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0017_assetmetrics_dashboardcache_aduser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicestatus",
            name="name",
            field=models.CharField(
                choices=[
                    ("active", "Spare"),
                    ("in_use", "In-Use"),
                    ("spare", "Retrieved"),
                    ("decommissioned", "Decommissioned"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
