# Generated by Django 6.0 on 2026-02-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0018_alter_devicestatus_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicestatus",
            name="name",
            field=models.CharField(
                choices=[
                    ("spare", "Spare"),
                    ("in-use", "In-Use"),
                    ("retrieved", "Retrieved"),
                    ("decommissioned", "Decommissioned"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
